const path = require('path');

// Set production environment
process.env.NODE_ENV = 'production';

// cPanel usually provides a PORT environment variable, but we can default it
process.env.PORT = process.env.PORT || 3000;

// Path to the standalone server generated by Next.js build
const standaloneServerPath = path.join(__dirname, '.next', 'standalone', 'server.js');

console.log(`Starting Baksho server from: ${standaloneServerPath}`);

try {
  // Bridge to the Next.js standalone server
  require(standaloneServerPath);
} catch (error) {
  console.error('Failed to start Baksho standalone server:', error);
  console.error('Ensure that "npm run build" has been executed and the ".next" folder is present.');
  process.exit(1);
}
